layout_spectrum: 0.16263010702095926
typography_spectrum: 0.3461648563388735
color:
  brandColors:
    - '#F2385A'
    - '#F5A503'
    - '#E9F1DF'
    - '#4AD9D9'
    - '#36B1BF'
  brandStrength: 0.3255758148152381
  lightness: 0.9695022909436375
  saturation: 0.1327410195954144
  rhythmicContrast: 0.5005251886323094
name: 'Beta Site: MostlyATourist'
favicon: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
