name: 'Beta Site: MostlyATourist'
favicon: null
layout_spectrum: 0.9887400851584971
typography_spectrum: 0.4528431149665266
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9311656535137445
  lightness: 0.0730315800756216
  saturation: 0.7105978911276907
  rhythmicContrast: 0.568353351438418
purpose: []
