layout_spectrum: 0.16235192911699414
typography_spectrum: 0.20528714288957417
color:
  brandColors:
    - '#F2385A'
    - '#F5A503'
    - '#E9F1DF'
    - '#4AD9D9'
    - '#36B1BF'
  brandStrength: 0.27196199097670615
  lightness: 0.4254801522474736
  saturation: 0.4084384059533477
  rhythmicContrast: 0.14614768791943789
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: 'Beta Site: MostlyATourist'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Theodore Roosevelt National Park
    id: f8c6c457-6416-44e3-bcc0-0308fe648a9e
    type: content
favicon: null
title: Mostly a Tourist
description: ...traveling the world for pleasure
purpose: []
