name: 'Beta Site: MostlyATourist'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49498
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.1875
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
