typography_spectrum: 0.5649978616274893
color:
  brandColors:
    - '#F2385A'
    - '#F5A503'
    - '#E9F1DF'
    - '#4AD9D9'
    - '#36B1BF'
  brandStrength: 0.3255758148152381
  lightness: 0.9695022909436375
  saturation: 0.1327410195954144
  rhythmicContrast: 0.5005251886323094
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: 'Beta Site: MostlyATourist'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Theodore Roosevelt National Park
    id: f8c6c457-6416-44e3-bcc0-0308fe648a9e
    type: content
favicon: null
title: Mostly a Tourist
description: 'tour·ist: a person who travels for pleasure'
purpose: []
