typography_spectrum: 0.4711709236726165
color:
  brandColors:
    - '#F2385A'
    - '#F5A503'
    - '#E9F1DF'
    - '#4AD9D9'
    - '#36B1BF'
  brandStrength: 0.27196199097670615
  lightness: 0.4254801522474736
  saturation: 0.4084384059533477
  rhythmicContrast: 0.14614768791943789
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8238686411641538
analytics:
  google: null
  facebook: null
  twitter: null
name: 'Beta Site: MostlyATourist'
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Mostly a Tourist
description: ...traveling the world for pleasure
purpose: []
